name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make IPA zip
        run: |
          mkdir -p Payload
          cp index.html Payload/ 2>/dev/null || true
          zip -r app.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-ios-app
          path: app.ipa
